@startuml
class Paper {
  + tittle: str
  + submitted_date: date
  + acceptance: bool
}

class Researcher {
  + name: str
  + institution: str
}

class ResearchEvent{
  + name: str
  + start: date
  + end: date
}

class Conference {
}

class Workshop {
}

class Symposium {
}

Paper "*" -- "1..*" Researcher: authors
ResearchEvent "*" -- "1..*" Researcher: organizers
ResearchEvent "1" *-- "*" Paper: papers
ResearchEvent <|-- Conference
ResearchEvent <|-- Workshop
ResearchEvent <|-- Symposium
@enduml
